name: Stage B- Test workflow

on:
  push:
    branches:
      main
      

jobs: 
  job-1:
    runs-on: ubuntu-latest

    steps:
      - name: print-welcome
        run: echo "Welcome"
        
      - name: print-hello
        run: echo "Hello"

  job-2:
    needs: job-1
    runs-on: ubuntu-latest
    steps:
      - name: print-stage
        run: echo "Currently in stage B"
      - name: print-stage-name
        run: echo "Stage B is introduction to Devops"
