name: Stage B- Test workflow

on:
  workflow_dispatch

jobs: 
  job-1:
    runs-on: ubuntu-latest

    steps:
      - name: print-welcome
        run: echo "Welcome"
        
      - name: print-hello
        run: echo "Hello"
